# Generated by Django 5.2.5 on 2025-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_api_product_availab_3e4621_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_verification_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Login Verification Code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_verification_code_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Code Expiry'),
        ),
    ]
