# Generated by Django 5.2.5 on 2025-12-06 22:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_account_lockout_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Quote Number')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('billing_address_json', models.JSONField(blank=True, null=True, verbose_name='Billing Address (JSON)')),
                ('shipping_address_json', models.JSONField(blank=True, null=True, verbose_name='Shipping Address (JSON)')),
                ('taxable_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Taxable Base (HT)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate (%)')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax Total (TVA)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Shipping Cost (HT)')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total TTC')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Order')], default='pending', max_length=20, verbose_name='Status')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('payment_terms', models.TextField(default='Paiement à la commande', verbose_name='Payment Terms')),
                ('delivery_time', models.CharField(default='2-5 jours ouvrables', max_length=100, verbose_name='Delivery Time')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='api.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU/Reference')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('options_description', models.CharField(blank=True, max_length=500, verbose_name='Options/Variants Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price HT')),
                ('line_total_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Line Total HT')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='api.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.quote')),
            ],
            options={
                'verbose_name': 'Quote Item',
                'verbose_name_plural': 'Quote Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='api_quote_quote_n_2e591f_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', '-created_at'], name='api_quote_user_id_5cdeac_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', '-created_at'], name='api_quote_status_537a50_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['valid_until'], name='api_quote_valid_u_b258f3_idx'),
        ),
    ]
