# Generated by GitHub Copilot on 2025-12-19

from __future__ import annotations

import secrets

from django.db import migrations, models


def _generate_token() -> str:
    # token_urlsafe(32) is ~43 chars; stays under 64.
    return secrets.token_urlsafe(32)


def ensure_access_token_column(apps, schema_editor):
    Quote = apps.get_model('api', 'Quote')
    table_name = Quote._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'access_token' not in columns:
        # Add the column in a vendor-neutral way.
        # We build the SQL using the field db_type for the current backend.
        access_token_field = models.CharField(max_length=64, null=True)
        db_type = access_token_field.db_type(schema_editor.connection)
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table_name)} "
            f"ADD COLUMN {schema_editor.quote_name('access_token')} {db_type}"
        )

    # Backfill any NULL/empty tokens (works both when column existed or was just added).
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT id FROM {schema_editor.quote_name(table_name)} "
            f"WHERE access_token IS NULL OR access_token = ''"
        )
        quote_ids = [row[0] for row in cursor.fetchall()]

    if not quote_ids:
        return

    for quote_id in quote_ids:
        token = _generate_token()
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f"UPDATE {schema_editor.quote_name(table_name)} "
                f"SET access_token = %s WHERE id = %s",
                [token, quote_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_quote_models'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # DB operation is handled via ensure_access_token_column() to avoid failing when
            # the column already exists (some deployments created it manually).
            database_operations=[
                migrations.RunPython(ensure_access_token_column, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='quote',
                    name='access_token',
                    field=models.CharField(
                        max_length=64,
                        unique=True,
                        db_index=True,
                        default=_generate_token,
                        editable=False,
                    ),
                ),
            ],
        ),
    ]
