# Generated by GitHub Copilot on 2025-12-19

from __future__ import annotations

import secrets

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_quote_access_token'),
    ]

    operations = [
        # State-only alignment: DB column already exists and is populated.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='quote',
                    name='access_token',
                    field=models.CharField(
                        max_length=64,
                        unique=True,
                        db_index=True,
                        default=secrets.token_urlsafe,
                        editable=False,
                        verbose_name=_("Access Token"),
                    ),
                ),
            ],
        ),
    ]
