# Generated by Django 5.2.5 on 2026-03-01 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(upload_to='products/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'xls', 'csv', 'txt', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_verification_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='Login Verification Code'),
        ),
    ]
